const fs = require('fs');
const path = require('path');
const archiver = require('archiver');
require('dotenv').config({ quiet: true });

const rootDir = path.resolve(__dirname, '..');
const sourceDir = path.join(rootDir, 'source');
const distDir = path.join(rootDir, 'dist');
const appDir = path.join(distDir, 'apps');
const buildDir = path.join(distDir, 'build');
const packageZip = path.join(appDir, 'tv-time-roku.zip');

function log(message, type = 'info') {
  const colors = {
    info: '\x1b[32m',
    error: '\x1b[31m',
    warn: '\x1b[33m',
    reset: '\x1b[0m'
  };

  const prefix = type === 'info' ? '==>' : `${type.toUpperCase()}:`;
  console.log(`${colors[type]}${prefix} ${message}${colors.reset}`);
}

function assertSource() {
  const manifestPath = path.join(sourceDir, 'manifest');

  if (!fs.existsSync(sourceDir)) {
    throw new Error(`Source directory not found: ${sourceDir}`);
  }

  if (!fs.existsSync(manifestPath)) {
    throw new Error(`Roku manifest not found: ${manifestPath}`);
  }
}

function copyDirectory(source, destination) {
  fs.cpSync(source, destination, { recursive: true });
}

function normalizeBackendAddress(backendUrl) {
  if (!backendUrl) return '';

  return backendUrl
    .trim()
    .replace(/^https?:\/\//, '')
    .replace(/\/.*$/, '');
}

function writeBuildConfig() {
  const backendAddress = normalizeBackendAddress(process.env.BACKEND_URL);
  const configPath = path.join(buildDir, 'source', 'Config.brs');
  const escapedBackendAddress = backendAddress.replace(/"/g, '""');
  const config = `' Generated by scripts/build.js. Do not edit.
function GetConfiguredBackendAddress() as string
    return "${escapedBackendAddress}"
end function
`;

  fs.writeFileSync(configPath, config);

  if (backendAddress) {
    log(`Configured backend: ${backendAddress}`);
  } else {
    log('No BACKEND_URL configured; Roku app will use discovery', 'warn');
  }
}

function createBuild() {
  assertSource();
  fs.rmSync(buildDir, { recursive: true, force: true });
  fs.mkdirSync(appDir, { recursive: true });

  if (fs.existsSync(packageZip)) {
    fs.unlinkSync(packageZip);
  }

  copyDirectory(sourceDir, buildDir);
  writeBuildConfig();

  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(packageZip);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', () => {
      log(`Package created: ${path.relative(rootDir, packageZip)}`);
      log(`Package size: ${(archive.pointer() / 1024).toFixed(2)} KB`);
      resolve();
    });

    archive.on('warning', (err) => {
      if (err.code === 'ENOENT') {
        log(err.message, 'warn');
        return;
      }

      reject(err);
    });

    archive.on('error', reject);
    output.on('error', reject);

    archive.pipe(output);
    archive.directory(buildDir, false);
    archive.finalize();
  });
}

createBuild().catch((err) => {
  log(`Build failed: ${err.message}`, 'error');
  process.exit(1);
});
